apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '{{ values.component_id }}'
  description: A simple Hello World Python application.
  annotations:
    # This is the corrected line 7
    github.com/project-slug: '{{ values.repoUrl | parseRepoUrl("owner") }}/{{ values.repoUrl | parseRepoUrl("repo") }}'
spec:
  type: service
  lifecycle: experimental
  owner: '{{ values.owner }}'