apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-hello-world-template
  title: Python Hello World Application
  description: Creates a simple Python "Hello World" application in your GitHub account.
spec:
  owner: builds-processes-squad
  type: service
  parameters:
    - title: Application Details
      required:
        - component_id
        - owner
      properties: 
        component_id:
          title: Name
          type: string
          description: Unique name of the application
        owner:
          title: Owner
          type: string
          description: Owner of the application
          ui:field: OwnerPicker
          ui:options: 
            allowedKinds: ['user']

    - title: Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ['github.com']
            allowedOwners: ['divinew-dojo']

  steps:
    # Step 1: Fetch the template and pass values for Cookiecutter to process.
    # This now includes repo_owner and repo_name for the annotations.
    - id: fetch_template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./template
        values:
          component_id: ${{ parameters.component_id }}
          owner: ${{ parameters.owner }}
          repo_owner: ${{ parameters.repoUrl | parseRepoUrl('owner') }}
          repo_name: ${{ parameters.repoUrl | parseRepoUrl('repo') }}

    # Step 2: Publish the fully rendered and correctly named files to GitHub.
    # The fs:rename step is no longer needed.
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'Initial commit for ${{ parameters.component_id }}'
        defaultBranch: main
    
    # Step 3: Register the component in the catalog. This will now succeed.
    - id: register 
      name: Register Component
      action: catalog:register
      input: 
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'