apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-hello-world-template
  title: Python Hello World Application
  description: Creates a simple Python "Hello World" application in your GitHub account.
spec:
  owner: builds-processes-squad
  type: service
  parameters:
    - title: Application Details
      required:
        - component_id
        - owner
      properties: 
        component_id:
          title: Name
          type: string
          description: Unique name of the application
        owner:
          title: owner
          type: string
          description: Owner of the application
          ui:field: OwnerPicker
          ui:options: 
            allowedKinds: ['user']

    - title: Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ['github.com']
            allowedOwners: ['divinew-dojo']

  steps:
    - id: fetch_skeleton
      name: Fetch Skeleton
      action: fetch:plain
      input:
        url: ./template
        targetPath: ./content
    
    - id: template
      name: Run Templating
      action: template:run
      input:
        path: './content'
        vlaues:
          component_id: ${{ parameters.component_id }}
          owner: ${{ parameters.owner }}
          repoUrl: ${{ parameters.repoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'Initial commit for ${{ parameters.component_id }}'
        defaultBranch: main
        sourcePath: './content'
    
    - id: register 
      name: Register Component
      action: catalog:register
      input: 
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'